

import type { Metadata } from 'next';
import './globals.css';
import { ReactQueryProvider } from '@/lib/react-query-provider';
import MyNavbar from '@/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-rose-50">
        <ReactQueryProvider>
          <MyNavbar />
          <main className="pt-20 px-4">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
